//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XiDeng.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XiDeng.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AliPay {
            get {
                object obj = ResourceManager.GetObject("AliPay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] arrow_63_240 {
            get {
                object obj = ResourceManager.GetObject("arrow_63_240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bengbengca {
            get {
                object obj = ResourceManager.GetObject("bengbengca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] book_128 {
            get {
                object obj = ResourceManager.GetObject("book_128", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] book_64 {
            get {
                object obj = ResourceManager.GetObject("book_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chart_4_240 {
            get {
                object obj = ResourceManager.GetObject("chart_4_240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] finish {
            get {
                object obj = ResourceManager.GetObject("finish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] home_6_240 {
            get {
                object obj = ResourceManager.GetObject("home_6_240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_audiotrack_white_96 {
            get {
                object obj = ResourceManager.GetObject("ic_audiotrack_white_96", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_query_builder_grey_600_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_query_builder_grey_600_36dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_settings_white_96 {
            get {
                object obj = ResourceManager.GetObject("ic_settings_white_96", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] layer_21_240 {
            get {
                object obj = ResourceManager.GetObject("layer_21_240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minus_5_240 {
            get {
                object obj = ResourceManager.GetObject("minus_5_240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] more_128 {
            get {
                object obj = ResourceManager.GetObject("more_128", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] one {
            get {
                object obj = ResourceManager.GetObject("one", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pexels_evgeny_tchebotarev_4101555 {
            get {
                object obj = ResourceManager.GetObject("pexels_evgeny_tchebotarev_4101555", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] plus_5_240 {
            get {
                object obj = ResourceManager.GetObject("plus_5_240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] recovery {
            get {
                object obj = ResourceManager.GetObject("recovery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] relax1 {
            get {
                object obj = ResourceManager.GetObject("relax1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] relax2 {
            get {
                object obj = ResourceManager.GetObject("relax2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] save_128 {
            get {
                object obj = ResourceManager.GetObject("save_128", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] series1 {
            get {
                object obj = ResourceManager.GetObject("series1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] series2 {
            get {
                object obj = ResourceManager.GetObject("series2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] series3 {
            get {
                object obj = ResourceManager.GetObject("series3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] series4 {
            get {
                object obj = ResourceManager.GetObject("series4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] series5 {
            get {
                object obj = ResourceManager.GetObject("series5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] series6 {
            get {
                object obj = ResourceManager.GetObject("series6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shake_sound {
            get {
                object obj = ResourceManager.GetObject("shake_sound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_1_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_1_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_10_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_10_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_10_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_10_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_2_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_2_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_3_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_3_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_4_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_4_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_5_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_5_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_6_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_6_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_6_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_7_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_7_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_7_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_7_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_8_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_8_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_8_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_8_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_9_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_9_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_1_Style_9_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_1_Style_9_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_1_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_1_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_10_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_10_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_10_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_10_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_2_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_2_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_3_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_3_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_4_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_4_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_5_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_5_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_6_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_6_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_6_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_7_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_7_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_7_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_7_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_8_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_8_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_8_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_8_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_9_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_9_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_2_Style_9_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_2_Style_9_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_1_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_1_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_10_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_10_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_10_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_10_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_2_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_2_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_3_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_3_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_4_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_4_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_5_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_5_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_6_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_6_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_6_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_7_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_7_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_7_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_7_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_8_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_8_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_8_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_8_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_9_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_9_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_3_Style_9_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_3_Style_9_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_1_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_1_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_10_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_10_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_10_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_10_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_2_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_2_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_3_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_3_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_4_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_4_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_5_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_5_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_6_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_6_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_6_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_7_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_7_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_7_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_7_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_8_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_8_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_8_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_8_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_9_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_9_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_4_Style_9_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_4_Style_9_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_1_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_1_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_10_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_10_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_2_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_2_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_3_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_3_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_4_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_4_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_5_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_5_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_6_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_6_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_6_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_7_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_7_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_8_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_8_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_5_Style_9_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_5_Style_9_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_1_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_1_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_10_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_10_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_2_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_3_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_3_2 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_4_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_5_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_6_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_7_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_7_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_8_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_8_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skill_6_Style_9_1 {
            get {
                object obj = ResourceManager.GetObject("Skill_6_Style_9_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] star_3_240 {
            get {
                object obj = ResourceManager.GetObject("star_3_240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] star_5_240 {
            get {
                object obj = ResourceManager.GetObject("star_5_240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] statistics_128 {
            get {
                object obj = ResourceManager.GetObject("statistics_128", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StatisticsBackImage {
            get {
                object obj = ResourceManager.GetObject("StatisticsBackImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] three {
            get {
                object obj = ResourceManager.GetObject("three", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] two {
            get {
                object obj = ResourceManager.GetObject("two", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] user_5_240 {
            get {
                object obj = ResourceManager.GetObject("user_5_240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] weather_116_240 {
            get {
                object obj = ResourceManager.GetObject("weather_116_240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeChatPay {
            get {
                object obj = ResourceManager.GetObject("WeChatPay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XiDengSkillsDataJson {
            get {
                object obj = ResourceManager.GetObject("XiDengSkillsDataJson", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xz {
            get {
                object obj = ResourceManager.GetObject("xz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] zm {
            get {
                object obj = ResourceManager.GetObject("zm", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
